{
 "title": "BGE Stem Night 2024",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature, Humidity, Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "humidity",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \r\nWHERE measure_name = 'humidity' AND room = 'Hanks'\r\nAND time between ago(15m) and now()\r\nORDER BY time \r\nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    },
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "humidity",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \r\nWHERE measure_name = 'humidity' AND room = 'Gonzalez'\r\nAND time between ago(15m) and now()\r\nORDER BY time \r\nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    },
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "temperature",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'humidity' AND room = 'Whitacre'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "pressure",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'pressure' AND room = 'Gonzalez'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    },
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "pressure",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'pressure' AND room = 'Hanks'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    },
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "pressure",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'pressure' AND room = 'Whitacre'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    }
   ]
  },
  {
   "title": "Average Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "temperature",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'temperature' AND room = 'Hanks'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    },
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "temperature",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'temperature' AND room = 'Gonzalez'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    },
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "temperature",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" \nWHERE measure_name = 'temperature' AND room = 'Whitacre'\nAND time between ago(15m) and now()\nORDER BY time \nDESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    }
   ]
  },
  { "title": "All timeseries data - combined", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Table View -- All Data",
   "type": "table",
   "gridPos": { "h": 16, "w": 21, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "\"TimestreamDataBase-5Q4JAkuI1q9a\"",
     "measure": "temperature",
     "rawQuery": "SELECT * FROM \"TimestreamDataBase-5Q4JAkuI1q9a\".\"TimestreamTable-l54viVXuxSVm\" WHERE time between ago(30m) and now() ORDER BY time DESC LIMIT 50",
     "table": "\"TimestreamTable-l54viVXuxSVm\""
    }
   ]
  }
 ]
}